#
# Copyright Protojure Project All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#

site_name: Protojure
site_url: http://protojure.readthedocs.io
theme: readthedocs
repo_url: https://github.com/protojure/readthedocs.git
site_description: 'Welcome to the Protojure documentation'
strict: true

nav:
- Introduction: intro.md
- Intallation: install.md
- Quick Start: quick-start.md
- Contribuing: contributing.md

markdown_extensions:
  - toc:
     permalink: true
  - admonition
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - footnotes
